### ISSUE TITLE
'favicon.ico' is not copied to build folder

### ISSUE THREAD

**Issue by peterbust** [websitejs2-0/websitejs#1]
The 'favicon.ico' file is not copied to the build folder which logs an error when trying to run 'gulp serve'. Which makes local development not possible.

Only '.svg' files are handled by 'svgicons.js', therefore the file is ignored. I don't think it would make sense to add it to 'svgicons.js' responsibility. I think it should be part of 'assets.js'.

Therefore I'd suggest to move the ico to '/assets/images/favicon.ico'. And add 'ico' to the array of files being handled in 'cleanAssets()' and 'compileAssets()'.

**Comment by roccojanse** [comment]
Added to assets gulp task indeed.
