### ISSUE TITLE
'console.clear();' throws an error on gulp serve.

### ISSUE THREAD

**Issue by peterbust** [websitejs2-0/websitejs#2]
'gulp serve' logs an error making local development not possible;

_TypeError: console.clear is not a function_
./gulpfile.js:23:9

If the line is removed everything works fine. I have a new cloned setup, fresh npm install and all required global dependencies. Absolutely no idea which causes the error.

![error](https://user-images.githubusercontent.com/25978569/30537387-ab44bba6-9c69-11e7-9182-c7dfa9d9ee54.jpg)

**Comment by roccojanse** [comment]
removed.
